os: WMF 5

skip_commits:
  message: /updated readme.*/

install:
  - ps: Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.201 -Confirm:$false -Force -ErrorAction Stop
  - ps: Install-Module -Name Pester -Force
  - ps: Install-Module -Name PSScriptAnalyzer -Force

build: false

test_script:
  - ps: . .\Tests\appveyor.pester.ps1
